baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "8"
summaryLength = "10"
theme = "github.com/adharshchottu/upsc-notes-theme"
title = "UPSC Notes"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "https://dodb-upsc.web.app/"
name = "DoDb Log"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "https://dodb-upsc.web.app/"
name = "DoDb"
weight = 4
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "adharsh"
description = "UPSC notes"
[params.banner]
heading = "#StickToThePlan"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "UPSC notes and questions for mains"
[params.call_to_action]
button_label = "Log now"
button_url = "https://dodb-upsc.web.app/"
content = "Log of daily activities"
enable = true
title = "Log Book"
[params.footer]
address = "you don't need a backup"
content = "keep calm and stay focused."
copyright = "#operationMEA"
hours = "until and unless you are in the ministry of external affairs"
title = "Do or Die"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = ""
facebook = ""
instagram = ""
linkedin = ""
twitter = ""
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
